apiVersion: v1
kind: Secret
metadata:
  labels: 
    app.kubernetes.io/instance: test-tempchatbot-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-tempchatbot-1 
  name: test-tempchatbot-1-model-config-secret
type: Opaque
data:
  MODEL_ENDPOINT_SECRET: {{ .Values.modelEndpointSecret | b64enc | quote }}
